Feature: ability to use nullable listener in useListenableSelector
rrousselGit/flutter_hooks pull request #377
Opened 2023-08-15 12:38 UTC by JWo1F

## Description

This Pull Request adds the ability to pass `null` as a parameter to the `useListenableSelector` hook. Previously, you could only pass a `Listener` instance, but now you can also pass `null` to the function.

This change is necessary when the listener is initialized later, for example, on the second render. By allowing `null` as a parameter, developers can delay the initialization of the listener until it's ready.

## Example Usage

```dart
// Before
useListenableSelector<SomeListener>(myListener, (state) => state.data);

// After
useListenableSelector<SomeListener?>(null, (state) => state?.data);

2023-08-16 07:39 UTC, rrousselGit commented
Nice. Could you add tests for this?

2023-08-16 07:39 UTC, rrousselGit requested changes
Needs testing :)

2023-08-17 18:28 UTC, JWo1F commented
@rrousselGit, I've added a test for this behaviour.

2023-08-17 18:36 UTC, JWo1F commented
I increased the test coverage by adding a check to ensure that everything functions correctly after the value appears.

2023-08-24 09:07 UTC, rrousselGit commented
Looks like some files are improperly formatted. Could you format them?

Hooks use the master channel, so you might have to switch channel to use the latest formatter

2023-08-24 18:27 UTC, JWo1F commented
@rrousselGit, seems to be done now, could you check it, please?

2023-08-29 06:10 UTC, merged

2023-08-29 06:10 UTC, rrousselGit commented
Thanks!

2023-08-29 06:12 UTC, rrousselGit commented
Available in flutter_hooks 0.20.1