add draggable_scrollable_controller
rrousselGit/flutter_hooks pull request #417
Opened 2024-02-25 20:24 UTC by dickermoshe

2024-02-26 09:56 UTC, davidmartos96 commented
I'd say this hook would benefit from the changes in https://github.com/rrousselGit/flutter_hooks/pull/415

Current implementation of `useDraggableScrollableController` is not disposing the `DraggableScrollableController`.

2024-02-26 12:46 UTC, dickermoshe commented
@davidmartos96 Good point!
I copied this from Expandable tile controller. I forgot that that isn't disposed.
I'll fix later

2024-02-26 13:57 UTC, dickermoshe commented
Fixed, if @rrousselGit plans on merging #415 I'll rebase and push

2024-02-28 11:15 UTC, rrousselGit commented on packages/flutter_hooks/lib/src/draggable_scrollable_controller.dart
> +    {List<Object?>? keys}) {
A little trailling comma would be great :)
```suggestion
    {List<Object?>? keys,}) {
```

2024-02-28 11:19 UTC, rrousselGit commented on packages/flutter_hooks/lib/src/draggable_scrollable_controller.dart
> +      : super(keys: keys);
```suggestion
  const _DraggableScrollableControllerHook({super.keys});
```

2024-02-28 11:20 UTC, rrousselGit approved these changes
LGTM after a little format change :)

2024-02-28 11:21 UTC, rrousselGit requested changes
Actually, could you add it to the README? And the changelog too, under the form of:

```dart
## Unreleased patch

- Added <...>
```

2024-02-28 14:07 UTC, dickermoshe commented
Done

2024-07-08 05:41 UTC, rrousselGit commented on packages/flutter_hooks/CHANGELOG.md
> +
```suggestion
```

2024-07-08 05:44 UTC, rrousselGit commented
LGTM thanks!

2024-07-08 05:44 UTC, rrousselGit approved these changes

2024-07-08 05:44 UTC, merged